[package]
name = "keeps_and_kobolds"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
better-std = { path = "../better-std", features = [ ] }
crokey = { version = "1.5.0", features = ["serde"] }
crossterm = { version = "0.29.0", features = ["serde"] }
derive_more = { version = "2.1.1", features = ["full"] }
directories = "6.0.0"
env_logger = "0.11.11"
include_directory = { version = "0.1.1", features = ["glob"] }
inventory = "0.3.24"
itertools = "0.15.0"
log = "0.4"
noise = "0.9.0"
pretty_assertions.workspace = true
protest = "1.1.0"
ratatui = "0.30.2"
redb = "4.2.0"
serde = { version = "1.0", features = ["derive"] }
signal-hook = "0.4.4"
simple-datetime-rs = { version = "0.3.0", features = ["serde"] }
tokio = { version = "1.53.1", features = ["full"] }
tokio-stream = "0.1.19"
toml = "1.1.4"
tui-markdown = "0.3.9"

libp2p = { version = "0.54", features = ["noise", "ping", "tcp", "tokio", "yamux"] }
futures = "0.3.30"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
